spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  application:
    name: api-gateway

  cloud:
    gateway:
      # websocket:
      #   enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: friendship-service
          uri: lb://friendship-service
          predicates:
            - Path=/api/friendships/**
          filters:
            - StripPrefix=1

        - id: chat-chats
          uri: lb://chat-service
          predicates:
            - Path=/api/chats/**
          filters:
            - StripPrefix=1

        - id: chat-groups
          uri: lb://chat-service
          predicates:
            - Path=/api/groups/**
          filters:
            - StripPrefix=1

        - id: chat-video-call
          uri: lb://chat-service
          predicates:
            - Path=/api/video-call/**
          filters:
            - StripPrefix=1
        
        - id: chat-group-video-call
          uri: lb://chat-service
          predicates:
            - Path=/api/group-video-call/**
          filters:
            - StripPrefix=1
            
        - id: chat-ws
          uri: lb://chat-service
          predicates:
            - Path=/api/ws/**
          filters:
            - StripPrefix=1
        # Ai
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/gemini/**
          filters:
            - StripPrefix=1
        # Poster-service
        - id: poster-service
          uri: lb://poster-service
          predicates:
            - Path=/api/posters/**
          filters:
            - StripPrefix=1

        - id: like-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/like-posters/**
          filters:
            - StripPrefix=1

        - id: comment-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/comments/**
          filters:
            - StripPrefix=1

        - id: notification-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: share-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/shares/**
          filters:
            - StripPrefix=1
            
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Báº­t CORS cho React
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "http://localhost:3000"
      #       allowedHeaders: "*"
      #       allowedMethods: GET,POST,PUT,DELETE,OPTIONS
      #       allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


---
spring:
  config:
    activate:
      on-profile: docker

  application:
    name: api-gateway

  cloud:
    gateway:
      # websocket:
      #   enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        # User-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        # Friendship-service
        - id: friendship-service
          uri: lb://friendship-service
          predicates:
            - Path=/api/friendships/**
          filters:
            - StripPrefix=1
        # chat-service
        - id: chat-chats
          uri: lb://chat-service
          predicates:
            - Path=/api/chats/**
          filters:
            - StripPrefix=1

        - id: chat-groups
          uri: lb://chat-service
          predicates:
            - Path=/api/groups/**
          filters:
            - StripPrefix=1

        - id: chat-video-call
          uri: lb://chat-service
          predicates:
            - Path=/api/video-call/**
          filters:
            - StripPrefix=1

        - id: chat-group-video-call
          uri: lb://chat-service
          predicates:
            - Path=/api/group-video-call/**
          filters:
            - StripPrefix=1
            
        - id: chat-ws
          uri: lb://chat-service
          predicates:
            - Path=/api/ws/**
          filters:
            - StripPrefix=1
        # Ai
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/gemini/**
          filters:
            - StripPrefix=1
        # Poster-service
        - id: poster-service
          uri: lb://poster-service
          predicates:
            - Path=/api/posters/**
          filters:
            - StripPrefix=1

        - id: like-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/like-posters/**
          filters:
            - StripPrefix=1

        - id: comment-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/comments/**
          filters:
            - StripPrefix=1

        - id: notification-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: share-poster
          uri: lb://poster-service
          predicates:
            - Path=/api/shares/**
          filters:
            - StripPrefix=1
        
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
